---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	search(search)
	get_graph_data(get_graph_data)
	get_latest_news(get_latest_news)
	ai_analysis(ai_analysis)
	__end__([<p>__end__</p>]):::last
	__start__ --> search;
	ai_analysis --> __end__;
	get_graph_data --> get_latest_news;
	get_latest_news --> ai_analysis;
	search --> get_graph_data;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
